### ISSUE TITLE
Can't access title bar anymore after installing the files.

### ISSUE THREAD

**Issue by Viper9081** [nieffka/bubble-clean-zen#2]
The userContent.css and userChrome.css has a bug which makes the titlebar unaccessible. Rest all is working fine, but I won't be able to use these CSS files bro as the presence of title bar is important to me.

![image](https://github.com/user-attachments/assets/062c7a0f-056c-4730-9c0e-083388a7252f)

**Comment by Viper9081** [comment]
Alright, I figured a solution. It's the `userChrome.css` that's causing the trouble with title bar. Just remove that and install any other userChrome CSS file you wish and you will be good with everything.

**Comment by nieffka** [comment]
If you want to show titlebar menu delete all of this line:

```
/* Hides Top Toolbar (single toolbar) */
:root[zen-single-toolbar="true"] #zen-appcontent-navbar-container {
  max-height: var(--zen-element-separation) !important;
}

:root[inDOMFullscreen="true"] #zen-appcontent-navbar-container {
  display: none !important;
}
```

 and then search `/* delete this to show */` , just remove the `display: none; `
