### ISSUE TITLE
If you want to show titlebar menu delete all of this line:

### ISSUE THREAD

**Issue by Viper9081** [nieffka/bubble-clean-zen#3]
If you want to show titlebar menu delete all of this line:

```
/* Hides Top Toolbar (single toolbar) */
:root[zen-single-toolbar="true"] #zen-appcontent-navbar-container {
  max-height: var(--zen-element-separation) !important;
}

:root[inDOMFullscreen="true"] #zen-appcontent-navbar-container {
  display: none !important;
}
```

 and then search `/* delete this to show */` , just remove the `display: none; `

_Originally posted by @nieffka in https://github.com/nieffka/bubble-clean-zen/issues/2#issuecomment-2554052817_

I have done the said corrections in the CSS file, and now the title bar does appear on hover, but the minimize, maximize and close buttons have disappeared.
![image](https://github.com/user-attachments/assets/e36e1d67-be75-4663-a003-620d428de2ff)

**Comment by nieffka** [comment]
![image](https://github.com/user-attachments/assets/36b2bbe0-18b1-40a6-a3ff-ab15c754215a)

do you do this?

**Comment by Viper9081** [comment]
Oh now I found. I tried to find it first (forgot Notepad has a Search feature😅). Now using the Search I found it...
